version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    container_name: ffc-main-db
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nestjs:
    build:
      dockerfile: Dockerfile
    image: nestjs
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    container_name: ffc-main-nestjs
    volumes:
      - .:/app

volumes:
  db:
