version: '3.7'

services:
  api:
    container_name: ffc-main-service
    image: node:18-alpine
    user: node
    working_dir: /home/node
    env_file: .env
    ports:
      - "${PORT:-3004}:3004"
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ffc-main-service-bdd
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  poke-db-data: {}
